### ISSUE TITLE
Requests Module missing

### ISSUE THREAD

**Issue by bhillard** [pzrsa/product-sniper#1]
What was the requests module?

**Comment by pzrsa** [comment]
Hey there, the requests module can be imported from a library.

In your terminal, you can do `pip3 install requests`

Also, you will need to install BeautifulSoup4. This can be done with again, `pip3 install bs4`

Alternatively, you can simply install both in one line with `pip3 install requests bs4`

Hope this helps. Sorry for the delay in replying.
