### ISSUE TITLE
Login module missing/error

### ISSUE THREAD

**Issue by basox70** [pzrsa/product-sniper#2]
The login module was not in requirements 
After doing `pip install -r requirements.txt`, I first got the error "ModuleNotFoundError: No module named 'login'"

And after executing "pip install login", I got this one "ImportError: cannot import name 'from_email' from 'login'"

The login module version installed is the 0.0.6

**Comment by pzrsa** [comment]
I just updated the documentation, the login was supposed to be a file with your details in it like the email and password. However you can just put in your details if you're not going to share it anyone.

Let me know if you come across any issues.
