### ISSUE TITLE
Not an issue but a noob question!

### ISSUE THREAD

**Issue by yvesmango** [pzrsa/product-sniper#3]
hello there, i'm also a beginning python learner. i was wondering what the purpose of the _time_ module at the bottom of app.py? does this mean that the app is hosted on a server ? otherwise, you'd have to keep this running in the background indefinitely correct?

**Comment by pzrsa** [comment]
hey, not a noob question and I'm glad you asked. `time.sleep(60)` simply runs the `check_availability` method every 60 seconds.

you can start the script on your own computer or a virtual machine (like Google Cloud compute engine or AWS ec2), then every 60 seconds it will run the search.

this is really old code, so its quite bad and confusing. if you need any support lmk and I could help with your learning journey!

**Comment by yvesmango** [comment]
thanks for the reply! i will close this "issue" and raise any future questions in the Discussions tab
